{{- if .Values.configMap.configServer.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  application.properties: |
    server.port=8888
    management.tracing.sampling.probability=1.0
    management.zipkin.tracing.endpoint=http://tracing-server-service:9411/api/v2/spans
    logging.level.io.micrometer.tracing=DEBUG
    logging.level.io.zipkin=DEBUG
    spring.cloud.config.server.git.uri=https://github.com/KhacThien88/spring-clinic-config-server
    spring.cloud.config.server.git.default-label=main
{{- end }}
