appName: promtail
env: dev
replicas: 1

service:
  port: 9080
  image: grafana/promtail:2.9.0
  lokiUrl: http://loki-server-service:3100
  scrapePaths:
    - /var/log/app.log
  labels:
    service: my-service
    job: promtail

ingress:
  enabled: false
  domainName: promtail-dev.khacthienit.click
  path: /
  pathType: Prefix

global:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"