appName: promtail
env: staging

service:
  port: 9080
  image: grafana/promtail:2.9.0
  lokiUrl: http://loki-server-service:3100/loki/api/v1/push
  labels:
    job: promtail
  scrapeConfigs:
    - job_name: petclinic
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - '*'
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          target_label: app
        - source_labels: [__meta_kubernetes_pod_annotation_promtail_io_logs]
          action: keep
          regex: true
      pipeline_stages:
        - regex:
            expression: '.*\[(?P<app>[^,]+),(?P<traceID>\w+),(?P<spanID>\w+)\].*'
            source: message
        - labels:
            traceID: traceID
            app: app
      __path__: /var/log/containers/*.log

ingress:
  enabled: false
  domainName: promtail-staging.khacthienit.click
  path: /
  pathType: Prefix

global:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"