appName: promtail
env: dev
service:
  port: 9080
  image: grafana/promtail:2.9.0
  lokiUrl: http://loki-server-service:3100/loki/api/v1/push
  labels:
    job: promtail
  scrapeConfigs:
    - job_name: zipkin
      static_configs:
        - targets:
            - localhost
          labels:
            job: zipkin
            app: tracing-server
            __path__: /var/log/containers/tracing-server-deployment*.log
      pipeline_stages:
        - regex:
            expression: '.*\[(?P<app>[^,]+),(?P<traceID>\w+),(?P<spanID>\w+)\].*'
            source: message
        - labels:
            traceID: traceID
            app: app
ingress:
  enabled: false
  domainName: promtail-dev.khacthienit.click
  path: /
  pathType: Prefix
global:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"