{{- if .Values.configMap.prometheus.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['prometheus-server-service.petclinic-review.svc.cluster.local:9090']
    - job_name: 'petclinic-api-gateway-static'
      static_configs:
      - targets: ['petclinic-api-gateway-service.petclinic-review.svc.cluster.local:8080']
        labels:
          app: petclinic-api-gateway
      metrics_path: /actuator/prometheus
    - job_name: 'petclinic-customers-service-static'
      static_configs:
      - targets: ['petclinic-customers-service-service.petclinic-review.svc.cluster.local:8081']
        labels:
          app: petclinic-customers-service
      metrics_path: /actuator/prometheus
    - job_name: 'petclinic-visits-service-static'
      static_configs:
      - targets: ['petclinic-visits-service-service.petclinic-review.svc.cluster.local:8082']
        labels:
          app: petclinic-visits-service
      metrics_path: /actuator/prometheus
    - job_name: 'petclinic-vets-service-static'
      static_configs:
      - targets: ['petclinic-vets-service-service.petclinic-review.svc.cluster.local:8083']
        labels:
          app: petclinic-vets-service
      metrics_path: /actuator/prometheus
    - job_name: 'petclinic-api-gateway'
      kubernetes_sd_configs:
      - role: service
        namespaces:
          names:
          - petclinic-review
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: ^petclinic-api-gateway-service$
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_namespace]
        target_label: __address__
        replacement: $1.$2.svc.cluster.local:8080
      - target_label: __metrics_path__
        replacement: /actuator/prometheus
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_service_name]
        target_label: service_name
      - source_labels: [__meta_kubernetes_service_label_app]
        target_label: app_label
      - source_labels: [__meta_kubernetes_service_port_name]
        target_label: port_name
    - job_name: 'petclinic-customers-service'
      kubernetes_sd_configs:
      - role: service
        namespaces:
          names:
          - petclinic-review
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: petclinic-customers-service-service
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
        target_label: __address__
        replacement: $2.$1.svc.cluster.local:8081
      - target_label: __metrics_path__
        replacement: /actuator/prometheus
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_service_name]
        target_label: service_name
    - job_name: 'petclinic-visits-service'
      kubernetes_sd_configs:
      - role: service
        namespaces:
          names:
          - petclinic-review
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: petclinic-visits-service-service
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
        target_label: __address__
        replacement: $2.$1.svc.cluster.local:8082
      - target_label: __metrics_path__
        replacement: /actuator/prometheus
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_service_name]
        target_label: service_name
    - job_name: 'petclinic-vets-service'
      kubernetes_sd_configs:
      - role: service
        namespaces:
          names:
          - petclinic-review
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: petclinic-vets-service-service
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
        target_label: __address__
        replacement: $2.$1.svc.cluster.local:8083
      - target_label: __metrics_path__
        replacement: /actuator/prometheus
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_service_name]
        target_label: service_name
    - job_name: 'debug-services'
      kubernetes_sd_configs:
      - role: service
        namespaces:
          names:
          - petclinic-review
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: petclinic-.*
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
        target_label: __address__
        replacement: $2.$1.svc.cluster.local
      - source_labels: [__meta_kubernetes_service_port_name]
        target_label: __port__
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_service_name]
        target_label: service_name
      - source_labels: [__meta_kubernetes_service_label_app]
        target_label: app_label
      - source_labels: [__meta_kubernetes_service_port_name]
        target_label: port_name
{{- end }}