{{- if .Values.configMap.prometheus.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']
    - job_name: 'petclinic'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - '*'
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        separator: ':'
        regex: (.+);(.+)
        target_label: __address__
      - target_label: __metrics_path__
        replacement: /actuator/prometheus
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
{{- end }}