{{- if .Values.configMap.prometheus.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['prometheus-server-service.petclinic-review.svc.cluster.local:9090']
    - job_name: 'petclinic-api-gateway'
      kubernetes_sd_configs:
      - role: service
        namespaces:
          names:
          - '*'
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: petclinic-api-gateway-service
      - source_labels: [__address__]
        action: replace
        regex: (.+?)(?::\d+)?$
        target_label: __address__
        replacement: $1:8080
      - target_label: __metrics_path__
        replacement: /actuator/prometheus
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
    - job_name: 'petclinic-customers-service'
      kubernetes_sd_configs:
      - role: service
        namespaces:
          names:
          - '*'
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: petclinic-customers-service-service
      - source_labels: [__address__]
        action: replace
        regex: (.+?)(?::\d+)?$
        target_label: __address__
        replacement: $1:8081
      - target_label: __metrics_path__
        replacement: /actuator/prometheus
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
    - job_name: 'petclinic-visits-service'
      kubernetes_sd_configs:
      - role: service
        namespaces:
          names:
          - '*'
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: petclinic-visits-service-service
      - source_labels: [__address__]
        action: replace
        regex: (.+?)(?::\d+)?$
        target_label: __address__
        replacement: $1:8082
      - target_label: __metrics_path__
        replacement: /actuator/prometheus
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
    - job_name: 'petclinic-vets-service'
      kubernetes_sd_configs:
      - role: service
        namespaces:
          names:
          - '*'
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: petclinic-vets-service-service
      - source_labels: [__address__]
        action: replace
        regex: (.+?)(?::\d+)?$
        target_label: __address__
        replacement: $1:8083
      - target_label: __metrics_path__
        replacement: /actuator/prometheus
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
{{- end }}