{{- if .Values.configMap.prometheus.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']
    - job_name: 'petclinic-api-gateway'
      static_configs:
      - targets: ['https://api-gateway-review.khacthienit.click']
      metrics_path: /actuator/prometheus
    - job_name: 'petclinic-customers-service'
      static_configs:
      - targets: ['https://customers-service-review.khacthienit.click']
      metrics_path: /actuator/prometheus
    - job_name: 'petclinic-vets-service'
      static_configs:
      - targets: ['https://vets-service-review.khacthienit.click']
      metrics_path: /actuator/prometheus
    - job_name: 'petclinic-visits-service'
      static_configs:
      - targets: ['https://visits-service-review.khacthienit.click']
      metrics_path: /actuator/prometheus
    - job_name: 'petclinic-genai-service'
      static_configs:
      - targets: ['https://genai-service-review.khacthienit.click']
      metrics_path: /actuator/prometheus
    - job_name: 'petclinic-admin-server'
      static_configs:
      - targets: ['https://admin-server-review.khacthienit.click']
      metrics_path: /actuator/prometheus
    - job_name: 'petclinic-config-server'
      static_configs:
      - targets: ['https://config-server-review.khacthienit.click']
      metrics_path: /actuator/prometheus
    - job_name: 'petclinic-discovery-server'
      static_configs:
      - targets: ['https://discovery-server-review.khacthienit.click']
      metrics_path: /actuator/prometheus
{{- end }}
