{{- if .Values.configMap.prometheus.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']
    - job_name: 'api-gateway'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - {{ .Release.Namespace }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: api-gateway
      - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        separator: ':'
        regex: (.+);(.+)
        target_label: __address__
        replacement: $1:8080
      - target_label: __metrics_path__
        replacement: /actuator/prometheus
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
    - job_name: 'customers-service'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - {{ .Release.Namespace }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: customers-service
      - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        separator: ':'
        regex: (.+);(.+)
        target_label: __address__
        replacement: $1:8081
      - target_label: __metrics_path__
        replacement: /actuator/prometheus
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
    - job_name: 'visits-service'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - {{ .Release.Namespace }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: visits-service
      - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        separator: ':'
        regex: (.+);(.+)
        target_label: __address__
        replacement: $1:8082
      - target_label: __metrics_path__
        replacement: /actuator/prometheus
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
    - job_name: 'vets-service'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - {{ .Release.Namespace }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: vets-service
      - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        separator: ':'
        regex: (.+);(.+)
        target_label: __address__
        replacement: $1:8083
      - target_label: __metrics_path__
        replacement: /actuator/prometheus
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
{{- end }}