appName: prometheus-server
env: dev
service:
  port: 9090
  image: prom/prometheus:latest
ingress:
  domainName: prometheus-server-dev.khacthienit.click
  path: /
  pathType: Prefix
global:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"