appName: loki-server
env: dev
service:
  port: 3100
  image:
    repository: grafana/loki
    tag: 3.1.1
ingress:
  domainName: loki-server-dev.khacthienit.click
  path: /
  pathType: Prefix
global:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"