appName: loki-server
env: dev
service:
  port: 3100
  image: grafana/loki:latest
ingress:
  domainName: loki-server-dev.khacthienit.click
  path: /
  pathType: Prefix
global:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"