apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}-deployment"
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      tolerations: {{ .Values.global.tolerations | toYaml | nindent 8 }}
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.service.image }}
          ports:
            - containerPort: {{ .Values.service.port }}
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/alertmanager
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.configMap.name }}