apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.appName }}-{{ .Values.env }}-config"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appName }}
    env: {{ .Values.env }}
data:
  promtail-config.yaml: |
    server:
      http_listen_port: {{ .Values.service.port }}
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: {{ .Values.service.lokiUrl }}/loki/api/v1/push
    scrape_configs:
      {{- range .Values.service.scrapeConfigs }}
      - job_name: {{ .job_name }}
        {{- if .kubernetes_sd_configs }}
        kubernetes_sd_configs:
          {{- toYaml .kubernetes_sd_configs | nindent 10 }}
        {{- end }}
        {{- if .relabel_configs }}
        relabel_configs:
          {{- toYaml .relabel_configs | nindent 10 }}
        {{- end }}
        pipeline_stages:
          {{- toYaml .pipeline_stages | nindent 10 }}
      {{- end }}