apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.appName }}-{{ .Values.env }}-config"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appName }}
    env: {{ .Values.env }}
data:
  promtail-config.yaml: |
    server:
      http_listen_port: {{ .Values.service.port }}
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: {{ .Values.service.lokiUrl }}/loki/api/v1/push
    scrape_configs:
      - job_name: {{ .Values.service.labels.job }}
        static_configs:
          - targets:
              - localhost
            labels:
              job: {{ .Values.service.labels.job }}
              service: {{ .Values.service.labels.service }}
              __path__: {{ join "," .Values.service.scrapePaths }}
        pipeline_stages:
          - json:
              expressions:
                traceID: traceID
                message: message
                service: service
          - labels:
              traceID: traceID
              service: service
          - match:
              selector: '{job="{{ .Values.service.labels.job }}"}'
              stages:
                - regex:
                    expression: "traceID=(?P<traceID>\w+)"
                    source: message
                - labels:
                    traceID: traceID