apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "{{ .Values.appName }}-{{ .Values.env }}-daemonset"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appName }}
    env: {{ .Values.env }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        env: {{ .Values.env }}
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      serviceAccountName: default
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.service.image }}
          args:
            - -config.file=/etc/promtail/promtail-config.yaml
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: logs
              mountPath: /var/log
          livenessProbe:
            enabled: false
          readinessProbe:
            enabled: false
      volumes:
        - name: config
          configMap:
            name: {{ .Values.appName }}-{{ .Values.env }}-config
        - name: logs
          hostPath:
            path: /var/log