{{- if .Values.configMap.vetsService.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  application.properties: |
    spring.application.name=vets-service
    spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://petclinic-config-server-service:8888/}
    spring.cache.cache-names=vets
    spring.zipkin.baseUrl=http://tracing-server-service:9411/api/v2/spans
    spring.sleuth.sampler.probability=1.0
{{- end }}