{{- if .Values.configMap.customersService.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  application.properties: |
    spring.application.name=customers-service
    spring.zipkin.baseUrl=http://tracing-server-service.petclinic-review.svc.cluster.local:9411/
    spring.sleuth.sampler.probability=1.0
    spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://petclinic-config-server-service:8888/}
{{- end }}