appName: grafana-server
env: staging
service:
  port: 3000
  image: grafana/grafana
  adminPassword: 111111aA
  datasources:
    prometheus:
      url: http://prometheus-server-service:9090
      type: prometheus
    loki:
      url: http:/loki-server-service:3100
      type: loki
    zipkin:
      url: http://tracing-server-service:9411
      type: zipkin
ingress:
  domainName: grafana-server.khacthienit.click
  path: /
  pathType: Prefix