apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracing-server-staging
  namespace: argocd  
spec:
  project: petclinic-staging
  source:
    repoURL: https://github.com/KhacThien88/spring-clinic-helm
    path: charts/tracing-server
    targetRevision: main
    helm:
      valueFiles:
        - staging-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace:  petclinic-staging  
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
