apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: alloy
    env: {{ .Values.env }}
data:
  config.alloy: {{ .Values.alloy.config | toYaml | quote }}