apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: petclinic-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Petclinic Development Project
  sourceRepos:
    - 'https://github.com/KhacThien88/spring-clinic-helm'
  destinations:
    - namespace: petclinic-dev
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'