{{- if .Values.configMap.visitsService.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  application.properties: |
    spring.application.name=visits-service
    management.zipkin.tracing.endpoint=http://tracing-server-service:9411/api/v2/spans
    spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://petclinic-config-server-service:8888/}
    spring.zipkin.baseUrl=http://tracing-server-service:9411/api/v2/spans
    spring.sleuth.sampler.probability=1.0
{{- end }}
