appName: otel-collector
env: dev
service:
  port: 4317
  zipkinPort: 9411
  metricsPort: 8889
  image: otel/opentelemetry-collector-contrib:latest
  type: ClusterIP
configMap:
  create: true
  name: otel-collector-configmap
loki:
  endpoint: "http://loki-server-service:3100/loki/api/v1/push"
global:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"